### ISSUE TITLE
Pesquisa sobre Protocolos

### ISSUE THREAD

**Issue by Phe0** [summer-job-2019-1-isi/LEAF#1]
### Descrição 

É necessário que haja um bom entendimento de protocolos de comunicação, para que sejam selecionados aqueles que a aplicação irá abranger.

### Tasks
 - [ ] Criar uma lista com diversos protocolos de comunicação
 - [ ] Levantar principais características de cada protocolo 
 - [ ] Levantar como os protocolos são afetados por cada um dos fatores externos 
 - [ ] Levantar o maior numero de interferências que afeta cada protocolo
 - [ ] Levantar formas de medir as interferências do protocolo
