### ISSUE TITLE
Apresentação de Pipeline do projeto

### ISSUE THREAD

**Issue by Phe0** [summer-job-2019-1-isi/LEAF#10]
### Descrição 
Confeccionar e apresentar uma pipeline de atividades para o projeto, explicando todo o processo da criação de uma atividade até seu termino 

### Tasks 
 - [x] Criar Organização
 - [x] Criar repositório
 - [x] Fazer README
 - [x] Fazer template de issue 
 - [x] Fazer template de pull request 
 - [x] Fazer issues das atividades já criadas 
 - [ ] Apresentar
