### ISSUE TITLE
Responder Relatório 4

### ISSUE THREAD

**Issue by Phe0** [summer-job-2019-1-isi/LEAF#5]
### Descrição 
Relatório para ser enviado ao CESAR, relacionado às atividades feitas na quarta semana 

### Tasks 
 - [x] No caso de mudança de planos, listar quais foram
 - [x] Listar  e explicar conflitos
 - [x] Listar e explicar conflitos
 - [x] Listar e explicar dificuldades técnicas
 - [x] Explicar como os problemas foram resolvidos 
 - [x] Explicar como a solução será prototipada

**Comment by KevinKAMS** [comment]
Relatório entregue
